version: '3.7'
services:
  httpd:
    build:
      context: ./httpd/build
      args:
        HTTPD_UID: ${HTTPD_UID:-www-data}
        HTTPD_GID: ${HTTPD_GID:-www-data}
    ports:
      - ${HTTPD_HOST_PORT:-80}:80
      - ${HTTPD_HOST_SSL_PORT:-443}:443
    volumes:
      - ./DocumentRoot:/var/www/html:z
      - phpmyadmin_data:/var/www/phpmyadmin:z,ro
      - certs:/certs:z
    depends_on:
      - sslcert-generator
      - php

  php:
    build:
      context: ./php/build/context
      dockerfile: ../Dockerfile-${PHP_VERSION:-74-fpm}
    user: ${PHP_FPM_UID:-1000}:${PHP_FPM_GID:-1000}
    environment:
      PHP_FPM_MAX_EXECUTION_TIME: ${PHP_FPM_MAX_EXECUTION_TIME:-600}
      PHP_FPM_MEMORY_LIMIT: ${PHP_FPM_MEMORY_LIMIT:-512M}
      PHP_FPM_POST_MAX_SIZE: ${PHP_FPM_POST_MAX_SIZE:-100M}
      PHP_FPM_UPLOAD_LIMIT: ${PHP_FPM_UPLOAD_LIMIT:-100M}
      PHP_FPM_ERROR_REPORTING: ${PHP_FPM_ERROR_REPORTING:-"E_ALL"}
      PHP_FPM_DISPLAY_ERRORS: ${PHP_FPM_DISPLAY_ERRORS:-"On"}
    volumes:
      - ./DocumentRoot:/var/www/html:z

  mariadb:
    image: docker.io/mariadb:10.5
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      TZ: ${TZ:-"Europe/Rome"}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD:-no}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpwd}
      MYSQL_USER: ${MYSQL_USER:-testuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-testpwd}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-testdb}

  phpmyadmin:
    image: docker.io/phpmyadmin:fpm
    links:
      - 'mariadb:db'
    environment:
      MAX_EXECUTION_TIME: ${PHP_FPM_MAX_EXECUTION_TIME:-600}
      MEMORY_LIMIT: ${PHP_FPM_MEMORY_LIMIT:-512M}
      UPLOAD_LIMIT: ${PHP_FPM_UPLOAD_LIMIT:-100M}
    volumes:
      - phpmyadmin_data:/var/www/html:z,ro
    depends_on:
      - mariadb

  sslcert-generator:
    image: docker.io/egdoc/docker-sslcert-generator
    environment:
      CERT_DAYS: ${CERT_DAYS:-365}
      CERT_COUNTRY: ${CERT_COUNTRY:-US}
      CERT_STATE: ${CERT_STATE:-"New York"}
      CERT_LOCALITY: ${CERT_LOCALITY:-Brooklin}
      CERT_ORGANIZATION_NAME: ${CERT_ORGANIZATION_NAME:-"Internet Widgits Pty Ltd"}
      CERT_COMMON_NAME: ${CERT_COMMON_NAME:-test.lan}
    volumes:
      - certs:/certs

volumes:
  mariadb:
  phpmyadmin_data:
  certs:
